version: '3'

networks:
  vuttr-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: vuttr-postgres
    environment:
      POSTGRES_DB: vuttr
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vuttr-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_PORT: 5432
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - vuttr-network

volumes:
  postgres-data:
