CREATE TABLE tag
(
    tool_id INTEGER      NOT NULL,
    tags    VARCHAR(255) NOT NULL
);

CREATE TABLE tool
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                             NOT NULL,
    link        VARCHAR(255)                             NOT NULL,
    description VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_tool PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT fk_tag_on_tool FOREIGN KEY (tool_id) REFERENCES tool (id);